### PR TITLE
placeholders and unused dependency

### PR DESCRIPTION
**Pull request by Vykook**
Hello, I just added placeholders for _EMAIL_ and _LOGIN_ and removed unused dependency.

### CODE REVIEW

**Comment by rkaldung** [comment]
@thorsteneckel  I'd like to see there the default variables provided by the template generator. Introducing new placeholders is a little bit disturbing to me.

**Comment by thorsteneckel** [comment]
@rkaldung  I agree with you to introduce limited static custom tags. We should allow the usage of all `User`-prefixed `$Self` attributes - except e.g. `UserPassword`.

**Comment by rkaldung** [comment]
@Vykook Would be great when you change the PR by using the template generator

**Comment by thorsteneckel** [comment]
No, don't use the template generator. The template generator is not suitable for this. As stated before: We should allow the usage of all `User`-prefixed `$Self` attributes - except e.g. `UserPassword`.

**Review by dennykorsukewitz — APPROVED** [review]

**Pull request merged**
